### ISSUE TITLE
aws.get_region() throws AttributeError: type object 'InvokeOptions' has no attribute 'merge' on version 5.11.0

### ISSUE THREAD

**Issue by rni34** [pulumi/pulumi-aws#2112]
### What happened?

After upgrading pulumi_aws to 5.11.0 getting AWS region throws an error

```  error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/user/.pulumi/bin/pulumi-language-python-exec", line 111, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
        return future.result()
      File "/home/user/myproject/infrastructure/venv/lib64/python3.7/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/user/myproject/infrastructure/venv/lib64/python3.7/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/home/user/myproject/infrastructure/venv/lib64/python3.7/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/user/myproject/infrastructure/venv/lib64/python3.7/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/home/user/.pulumi/bin/pulumi-language-python-exec", line 110, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib64/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 147, in <module>
        pulumi.export("aws-region", aws.get_region())
      File "/home/user/myproject/infrastructure/venv/lib64/python3.7/site-packages/pulumi_aws/get_region.py", line 113, in get_region
        opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'
```

### Steps to reproduce

```
    import pulumi
    import pulumi_aws as aws

    current = aws.get_region()
```

### Expected Behavior

Returning a dictionary looking like this
```
{
      + description: "US East (N. Virginia)"
      + endpoint   : "ec2.us-east-1.amazonaws.com"
      + id         : "us-east-1"
      + name       : "us-east-1"
    }
```

### Actual Behavior

```
File "/home/user/myproject/infrastructure/venv/lib64/python3.7/site-packages/pulumi_aws/get_region.py", line 113, in get_region
        opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'

```

### Output of `pulumi about`

```
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.11.0
aws-native    0.19.0
awsx          1.0.0-beta.8
docker        3.2.0
mongodbatlas  3.2.0
python        unknown

Host
OS       amazon
Version  2
Arch     x86_64

This project is written in python: executable='/home/user/myproject/infrastructure/venv/bin/python3' version='3.7.10
'
```

### Additional context

For now, I have downgraded to pulumi-aws==5.10.0  which runs aws.get_region()  fine

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @rni34 - thank you for reporting - I'll take a look at this for you.

**Comment by guineveresaenger** [comment]
Hi @rni34 - I verified this is no longer an issue in pulumi-aws v5.13 - you can safely upgrade to the newest version and it should work as expected:
```
pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/guinevere/aws-2112/dev/previews/fb6bf6d1-484d-4665-878c-8bd6eb742cb3

     Type                 Name          Plan     
     pulumi:pulumi:Stack  aws-2112-dev           
 
Outputs:
  + region: {
      + description: "US West (Oregon)"
      + endpoint   : "ec2.us-west-2.amazonaws.com"
      + id         : "us-west-2"
      + name       : "us-west-2"
    }
```

**Comment by rni34** [comment]
Hi @guineveresaenger 
I recently upgraded to 5.13 and it's still happening again. Please have a look at this link below,
it's still throwing this error,
```File "/home/user/myproject/infrastructure/venv/lib64/python3.7/site-packages/pulumi_aws/get_region.py", line 113, in get_region
        opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'
```
I can see that code in here as well 
https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/get_region.py#:~:text=%20opts%20%3D%20pulumi.invokeoptions.merge(_utilities.get_invoke_opts_defaults()%2C%20opts)

Thank you

**Comment by smcoll** [comment]
Same. i just had this issue with 5.41.0.

**Comment by smcoll** [comment]
Interesting: the iws-activity-reporter didn't have the AWS_LAMBDA_BASIC_EXECUTION_ROLE policy, and apparently hasn't needed it. i suppose one of the other attached policies is inclusive.

```
$ pulumi up
Previewing update (iws-activity-reporter-dev):
     Type                                             Name                                                                   Plan       
     pulumi:pulumi:Stack                              OmniChannel-omni-engine-iws-activity-reporter-dev                                 
 +   ├─ revspring:pulumi_helpers:ContainerizedLambda  iws-activity-reporter                                                  create     
 +   └─ aws:iam:RolePolicyAttachment                  iam-dev-iws-activity-reporter-fn-role-basic-execution-role-attachment  create     


Resources:
    + 2 to create
    20 unchanged
```
