### ISSUE TITLE
node_modules aren't pushed to Lambda

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-aws#50]
I deployed this code (https://github.com/lindydonna/pulumi-cloud/tree/79dd1757078fa37122c422a00ddbb5117b3e4160/examples/url-shortener) which took a dependency on the `redis` module. It looks like the module didn't get uploaded, because I saw this error in CloudWatch:

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module 'redis'

Contents of stacks/testing.json:
[testing.json](https://github.com/pulumi/pulumi-cloud/files/1409502/testing.json.txt)

According to Luke, the regression was likely in https://github.com/pulumi/pulumi-aws/commit/d08a0d5981cb3dc62d0fc3b35174c492e7f84c85

CC @joeduffy
