### ISSUE TITLE
gcp.storage.get_project_service_account() throws AttributeError: type object 'InvokeOptions' has no attribute 'merge' on version 6.43.0

### ISSUE THREAD

**Issue by tejaswinibussety** [pulumi/pulumi-aws#2216]
### What happened?

After upgrading pulumi_gcp to 6.43.0, I see the below crash
```bash
File "test.py", line 360, in handle
        gcs_account = gcp.storage.get_project_service_account()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi_gcp/storage/get_project_service_account.py", line 168, in get_project_service_account
        opts = pulumi.InvokeOptions.merge(
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'
    error: an unhandled error occurred: python inline source runtime error: type object 'InvokeOptions' has no attribute 'merge'
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/automation/_server.py", line 69, in Run
        loop.run_until_complete(run_in_stack(self.program))
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
        return future.result()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "test.py", line 360, in handle
        gcs_account = gcp.storage.get_project_service_account()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi_gcp/storage/get_project_service_account.py", line 168, in get_project_service_account
        opts = pulumi.InvokeOptions.merge(
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'
```

### Steps to reproduce

```bash
import pulumi_gcp as gcp
def handle():
    gcs_account = gcp.storage.get_project_service_account()
    pulumi.export("gcs_account", gcs_account.email_address)

project_name = "services"
stack_name = "test"
stack = auto.create_or_select_stack(stack_name=stack_name,
                                    project_name=project_name,
                                    program=handle)
stack.up(on_output=print)
```

### Expected Behavior

Return gcs_account object with email_address pointing to my project's GCS Storage Service Account

### Actual Behavior

File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pulumi_gcp/storage/get_project_service_account.py", line 168, in get_project_service_account
        opts = pulumi.InvokeOptions.merge(
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'

### Output of `pulumi about`

I'm using automation API and not pulumi engine directly, the below is my requirement.txt
```
requests
pulumi>=3.0.0,<4.0.0
pulumi-aws>=5.0.0,<6.0.0
pulumi-mysql==3.1.0
pulumi-kubernetes==3.19.3
pulumi-random==4.8.0
ruamel.yaml.clib==0.2.6; python_version < '3.10' and platform_python_implementation == 'CPython'
ruamel.yaml==0.17.16
deepmerge==1.0.1
boto3==1.24.12
chevron==0.14.0
GitPython==3.1.27
kubernetes==11.0.0
pulumi-gcp==6.43.0
```

### Additional context

For now, I have downgraded to pulumi-gcp==6.32.0 which runs gcs_account = gcp.storage.get_project_service_account() fine

Looks like https://github.com/pulumi/pulumi-gcp/commit/6aa7a22da233d5b098c932a50a0e25c8d4d90804#diff-5170990f4fe27fd148ef6ff1879f4944e4ae60e7944972c463a65af5383d7027 change has something to do with the issue

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @tejaswinibussety, sorry you're running into trouble here. What version of Pulumi and the SDK is your program using, exactly? The 3.0-4.0 range from requirements.txt is very wide.

**Comment by tejaswinibussety** [comment]
Hi @thomas11 , Thanks for getting back. Please find the versions I'm using below
```bash
tejaswinib% pip3 list | grep pulumi
pulumi                    3.34.1
pulumi-aws                5.8.0
pulumi-aws-native         0.19.0
pulumi-gcp                6.32.0
pulumi-kubernetes         3.19.3
pulumi-mysql              3.1.0
pulumi-random             4.8.0
```

**Comment by thomas11** [comment]
Thank you @tejaswinibussety! Looking through our history, I see that `InvokeOptions.merge` [was introduced in version 3.35.0](https://github.com/pulumi/pulumi/commit/aae9c20ffc4c386994a9cc5208826315d3048542). It seems that your upgrade to a newer gcp provider requires a pulumi version of at least 3.35. Apologies for the imprecise requirements.txt here! Could you try if an upgrade solves your issue?

**Comment by tejaswinibussety** [comment]
Thanks @thomas11 upgrading pulumi version worked..!
