### ISSUE TITLE
V6: property SDK does not exist

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#2676]
### What happened?

```
- TestAccAwsTsTwitterAthena
  index.ts(75,24): error TS2339: Property 'sdk' does not exist on type 'typeof import("/tmp/p-it-fv-az1100--aws-ts-twi-dd38a5b2-2392224114/node_modules/@pulumi/aws/index")'.

- TestAccAwsTsS3LambdaCopyZip
  index.ts(13,24): error TS2339: Property 'sdk' does not exist on type 'typeof import("/tmp/p-it-fv-az1100--aws-ts-s3--4921905c-1616601996/node_modules/@pulumi/aws/index")'.

```

### Expected Behavior

Preserve previous behavior.

### Steps to reproduce

```typescript
    import * as aws from "@pulumi/aws";

    const s3 = new aws.sdk.S3();
    await s3.putObject({
        Bucket: bucket.id.get(),
        Key: filename,
        Body: contents,
    }).promise();
```

### Output of `pulumi about`

N/A

### Additional context

Extracted from failing tests on pulumi/examples when updating to v6.0.0.alpha.8.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
This is the change documented at https://github.com/pulumi/registry/pull/2941/files#diff-cf20357c0b186a90302f1aca11481c919575f7fffed60e35fdb6a2abe28cc54dR162 in the migration guide. Those changes will need to be applied to these examples (including adding direct aws SDK v3 dependencies to these examples)

**Comment by mnlumi** [comment]
Closed as by design
